name: Continuous Integration

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm ci
        npm run build

    - name: Test
      run: |
        npm run test
        npm run lint

    - name: Coverage
      run: |
        npm run coverage
    
    - name: Archive code coverage
      uses: actions/upload-artifact@v4
      with:
        name: code-coverage-report
        path: coverage

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-region: ${{ secrets.AWS_REGION }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: Pulumi Preview
      uses: pulumi/actions@v6
      with:
        command: preview
        stack-name: pg94au/2BitBlaster/2BitBlaster
        work-dir: deployment
      env:
        PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}